
#define VK_INSTANCE_FUNCS \
    FORVKFUNC(DestroyInstance) \
    FORVKFUNC(EnumerateDeviceExtensionProperties) \
    FORVKFUNC(GetPhysicalDeviceFeatures2) \
    FORVKFUNC(GetInstanceProcAddr) \
    FORVKFUNC(GetPhysicalDeviceFormatProperties) \
    FORVKFUNC(GetPhysicalDeviceMemoryProperties) \
    FORVKFUNC(GetPhysicalDeviceQueueFamilyProperties) \
    FORVKFUNC(GetPhysicalDeviceProperties)

#define VK_DEVICE_FUNCS \
    FORVKFUNC(AllocateCommandBuffers) \
    FORVKFUNC(AllocateDescriptorSets) \
    FORVKFUNC(AllocateMemory) \
    FORVKFUNC(BeginCommandBuffer) \
    FORVKFUNC(BindBufferMemory) \
    FORVKFUNC(BindImageMemory) \
    FORVKFUNC(CmdBeginRenderPass) \
    FORVKFUNC(CmdBeginRenderPass2) \
    FORVKFUNC(CmdBeginRenderPass2KHR) \
    FORVKFUNC(CmdBeginRendering) \
    FORVKFUNC(CmdBeginRenderingKHR) \
    FORVKFUNC(CmdBindDescriptorSets) \
    FORVKFUNC(CmdBindIndexBuffer) \
    FORVKFUNC(CmdBindPipeline) \
    FORVKFUNC(CmdBindVertexBuffers) \
    FORVKFUNC(CmdBlitImage) \
    FORVKFUNC(CmdCopyBufferToImage) \
    FORVKFUNC(CmdCopyImageToBuffer) \
    FORVKFUNC(CmdCopyImage) \
    FORVKFUNC(CmdExecuteCommands) \
    FORVKFUNC(CmdClearColorImage) \
    FORVKFUNC(CmdDispatch) \
    FORVKFUNC(CmdDraw) \
    FORVKFUNC(CmdDrawIndexed) \
    FORVKFUNC(CmdDrawIndirect) \
    FORVKFUNC(CmdDrawIndexedIndirect) \
    FORVKFUNC(CmdDrawIndirectCount) \
    FORVKFUNC(CmdDrawIndirectCountKHR) \
    FORVKFUNC(CmdDrawIndexedIndirectCount) \
    FORVKFUNC(CmdDrawIndexedIndirectCountKHR) \
    FORVKFUNC(CmdEndRenderPass) \
    FORVKFUNC(CmdEndRenderPass2) \
    FORVKFUNC(CmdEndRenderPass2KHR) \
    FORVKFUNC(CmdEndRendering) \
    FORVKFUNC(CmdEndRenderingKHR) \
    FORVKFUNC(CmdPipelineBarrier) \
    FORVKFUNC(CmdPushConstants) \
    FORVKFUNC(CmdSetScissor) \
    FORVKFUNC(CmdSetViewport) \
    FORVKFUNC(CreateBuffer) \
    FORVKFUNC(CreateCommandPool) \
    FORVKFUNC(CreateDescriptorPool) \
    FORVKFUNC(CreateDescriptorSetLayout) \
    FORVKFUNC(CreateFence) \
    FORVKFUNC(CreateFramebuffer) \
    FORVKFUNC(CreateGraphicsPipelines) \
    FORVKFUNC(CreateComputePipelines) \
    FORVKFUNC(CreateImage) \
    FORVKFUNC(CreateImageView) \
    FORVKFUNC(CreatePipelineLayout) \
    FORVKFUNC(CreateRenderPass) \
    FORVKFUNC(CreateRenderPass2) \
    FORVKFUNC(CreateRenderPass2KHR) \
    FORVKFUNC(CreateSampler) \
    FORVKFUNC(CreateSemaphore) \
    FORVKFUNC(CreateShaderModule) \
    FORVKFUNC(CreateSwapchainKHR) \
    FORVKFUNC(DestroyBuffer) \
    FORVKFUNC(DestroyCommandPool) \
    FORVKFUNC(DestroyDescriptorPool) \
    FORVKFUNC(DestroyDescriptorSetLayout) \
    FORVKFUNC(DestroyDevice) \
    FORVKFUNC(DestroyFence) \
    FORVKFUNC(DestroyFramebuffer) \
    FORVKFUNC(DestroyImage) \
    FORVKFUNC(DestroyImageView) \
    FORVKFUNC(DestroyPipeline) \
    FORVKFUNC(DestroyPipelineLayout) \
    FORVKFUNC(DestroyRenderPass) \
    FORVKFUNC(DestroySampler) \
    FORVKFUNC(DestroySemaphore) \
    FORVKFUNC(DestroyShaderModule) \
    FORVKFUNC(DestroySwapchainKHR) \
    FORVKFUNC(EndCommandBuffer) \
    FORVKFUNC(FlushMappedMemoryRanges) \
    FORVKFUNC(FreeCommandBuffers) \
    FORVKFUNC(FreeDescriptorSets) \
    FORVKFUNC(FreeMemory) \
    FORVKFUNC(GetBufferMemoryRequirements) \
    FORVKFUNC(GetDeviceFaultInfoEXT) \
    FORVKFUNC(GetDeviceProcAddr) \
    FORVKFUNC(GetDeviceQueue) \
    FORVKFUNC(GetDeviceQueue2) \
    FORVKFUNC(GetImageMemoryRequirements) \
    FORVKFUNC(GetQueueCheckpointData2NV) \
    FORVKFUNC(GetQueueCheckpointDataNV) \
    FORVKFUNC(GetSwapchainImagesKHR) \
    FORVKFUNC(MapMemory) \
    FORVKFUNC(CmdSetCheckpointNV) \
    FORVKFUNC(QueuePresentKHR) \
    FORVKFUNC(QueueSubmit) \
    FORVKFUNC(QueueWaitIdle) \
    FORVKFUNC(ResetCommandPool) \
    FORVKFUNC(ResetFences) \
    FORVKFUNC(UnmapMemory) \
    FORVKFUNC(UpdateDescriptorSets) \
    FORVKFUNC(WaitForFences)
